# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_add_group.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormAddGroup(object):
    def setupUi(self, FormAddGroup):
        FormAddGroup.setObjectName("FormAddGroup")
        FormAddGroup.resize(285, 220)
        FormAddGroup.setStyleSheet("background-color: rgb(198, 198, 198);")
        self.centralwidget = QtWidgets.QWidget(FormAddGroup)
        self.centralwidget.setObjectName("centralwidget")
        self.edit_name_group = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_name_group.setEnabled(True)
        self.edit_name_group.setGeometry(QtCore.QRect(20, 35, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.edit_name_group.setFont(font)
        self.edit_name_group.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_name_group.setObjectName("edit_name_group")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.cb_curator_group = QtWidgets.QComboBox(self.centralwidget)
        self.cb_curator_group.setGeometry(QtCore.QRect(20, 110, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_curator_group.setFont(font)
        self.cb_curator_group.setCurrentText("")
        self.cb_curator_group.setObjectName("cb_curator_group")
        self.btn_add_group = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_group.setGeometry(QtCore.QRect(20, 160, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add_group.setFont(font)
        self.btn_add_group.setStyleSheet("QPushButton {background-color: rgb(133, 125, 86); \n"
"color: White; border-radius: 10px;}\n"
"QPushButton:pressed {background-color:rgb(43, 252, 50) ; }")
        self.btn_add_group.setAutoDefault(False)
        self.btn_add_group.setDefault(False)
        self.btn_add_group.setFlat(False)
        self.btn_add_group.setObjectName("btn_add_group")
        FormAddGroup.setCentralWidget(self.centralwidget)

        self.retranslateUi(FormAddGroup)
        QtCore.QMetaObject.connectSlotsByName(FormAddGroup)

    def retranslateUi(self, FormAddGroup):
        _translate = QtCore.QCoreApplication.translate
        FormAddGroup.setWindowTitle(_translate("FormAddGroup", "Форма добавления группы"))
        self.edit_name_group.setPlaceholderText(_translate("FormAddGroup", "Название группы"))
        self.label.setText(_translate("FormAddGroup", "Введите название группы"))
        self.label_4.setText(_translate("FormAddGroup", "Куратор группы"))
        self.btn_add_group.setText(_translate("FormAddGroup", "Добавить группу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormAddGroup = QtWidgets.QMainWindow()
    ui = Ui_FormAddGroup()
    ui.setupUi(FormAddGroup)
    FormAddGroup.show()
    sys.exit(app.exec_())
