# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_change_curator_for_group.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormChangeCurator(object):
    def setupUi(self, FormChangeCurator):
        FormChangeCurator.setObjectName("FormChangeCurator")
        FormChangeCurator.resize(301, 230)
        FormChangeCurator.setStyleSheet("background-color: rgb(198, 198, 198);")
        self.centralwidget = QtWidgets.QWidget(FormChangeCurator)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 0, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 70, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.cb_change_curator_group = QtWidgets.QComboBox(self.centralwidget)
        self.cb_change_curator_group.setGeometry(QtCore.QRect(30, 100, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_change_curator_group.setFont(font)
        self.cb_change_curator_group.setCurrentText("")
        self.cb_change_curator_group.setObjectName("cb_change_curator_group")
        self.btn_add_group = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_group.setGeometry(QtCore.QRect(29, 150, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add_group.setFont(font)
        self.btn_add_group.setStyleSheet("QPushButton {background-color: rgb(133, 125, 86); \n"
"color: White; border-radius: 10px;}\n"
"QPushButton:pressed {background-color:rgb(43, 252, 50) ; }")
        self.btn_add_group.setAutoDefault(False)
        self.btn_add_group.setDefault(False)
        self.btn_add_group.setFlat(False)
        self.btn_add_group.setObjectName("btn_add_group")
        self.cb_choice_group = QtWidgets.QComboBox(self.centralwidget)
        self.cb_choice_group.setGeometry(QtCore.QRect(30, 30, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_choice_group.setFont(font)
        self.cb_choice_group.setCurrentText("")
        self.cb_choice_group.setObjectName("cb_choice_group")
        FormChangeCurator.setCentralWidget(self.centralwidget)

        self.retranslateUi(FormChangeCurator)
        QtCore.QMetaObject.connectSlotsByName(FormChangeCurator)

    def retranslateUi(self, FormChangeCurator):
        _translate = QtCore.QCoreApplication.translate
        FormChangeCurator.setWindowTitle(_translate("FormChangeCurator", "Форма изменения куратора"))
        self.label.setText(_translate("FormChangeCurator", "Выберите группу"))
        self.label_4.setText(_translate("FormChangeCurator", "Выберите нового куратора"))
        self.btn_add_group.setText(_translate("FormChangeCurator", "Добавить изменения"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormChangeCurator = QtWidgets.QMainWindow()
    ui = Ui_FormChangeCurator()
    ui.setupUi(FormChangeCurator)
    FormChangeCurator.show()
    sys.exit(app.exec_())
