# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_change_group_for_curator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormChangeGroup(object):
    def setupUi(self, FormChangeGroup):
        FormChangeGroup.setObjectName("FormChangeGroup")
        FormChangeGroup.resize(270, 250)
        FormChangeGroup.setStyleSheet("background-color: rgb(198, 198, 198);")
        self.centralwidget = QtWidgets.QWidget(FormChangeGroup)
        self.centralwidget.setObjectName("centralwidget")
        self.cb_choice_curator = QtWidgets.QComboBox(self.centralwidget)
        self.cb_choice_curator.setGeometry(QtCore.QRect(21, 40, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_choice_curator.setFont(font)
        self.cb_choice_curator.setCurrentText("")
        self.cb_choice_curator.setObjectName("cb_choice_curator")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(21, 80, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(21, 10, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cb_change_group = QtWidgets.QComboBox(self.centralwidget)
        self.cb_change_group.setGeometry(QtCore.QRect(21, 110, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_change_group.setFont(font)
        self.cb_change_group.setCurrentText("")
        self.cb_change_group.setObjectName("cb_change_group")
        self.btn_add_change = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_change.setGeometry(QtCore.QRect(20, 160, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add_change.setFont(font)
        self.btn_add_change.setStyleSheet("QPushButton {background-color: rgb(133, 125, 86); \n"
"color: White; border-radius: 10px;}\n"
"QPushButton:pressed {background-color:rgb(43, 252, 50) ; }")
        self.btn_add_change.setAutoDefault(False)
        self.btn_add_change.setDefault(False)
        self.btn_add_change.setFlat(False)
        self.btn_add_change.setObjectName("btn_add_change")
        FormChangeGroup.setCentralWidget(self.centralwidget)

        self.retranslateUi(FormChangeGroup)
        QtCore.QMetaObject.connectSlotsByName(FormChangeGroup)

    def retranslateUi(self, FormChangeGroup):
        _translate = QtCore.QCoreApplication.translate
        FormChangeGroup.setWindowTitle(_translate("FormChangeGroup", "Форма изменения группы"))
        self.label_4.setText(_translate("FormChangeGroup", "Выберите новую группу"))
        self.label.setText(_translate("FormChangeGroup", "Выберите куратора"))
        self.btn_add_change.setText(_translate("FormChangeGroup", "Добавить изменения"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormChangeGroup = QtWidgets.QMainWindow()
    ui = Ui_FormChangeGroup()
    ui.setupUi(FormChangeGroup)
    FormChangeGroup.show()
    sys.exit(app.exec_())
