# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_add_curator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormAddCurator(object):
    def setupUi(self, FormAddCurator):
        FormAddCurator.setObjectName("FormAddCurator")
        FormAddCurator.resize(275, 140)
        FormAddCurator.setStyleSheet("background-color: rgb(198, 198, 198);")
        self.centralwidget = QtWidgets.QWidget(FormAddCurator)
        self.centralwidget.setObjectName("centralwidget")
        self.edit_name_curator = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_name_curator.setEnabled(True)
        self.edit_name_curator.setGeometry(QtCore.QRect(21, 35, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.edit_name_curator.setFont(font)
        self.edit_name_curator.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_name_curator.setObjectName("edit_name_curator")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(21, 10, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_add_curator = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_curator.setGeometry(QtCore.QRect(20, 80, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add_curator.setFont(font)
        self.btn_add_curator.setStyleSheet("QPushButton {background-color: rgb(133, 125, 86); \n"
"color: White; border-radius: 10px;}\n"
"QPushButton:pressed {background-color:rgb(43, 252, 50) ; }")
        self.btn_add_curator.setAutoDefault(False)
        self.btn_add_curator.setDefault(False)
        self.btn_add_curator.setFlat(False)
        self.btn_add_curator.setObjectName("btn_add_curator")
        FormAddCurator.setCentralWidget(self.centralwidget)

        self.retranslateUi(FormAddCurator)
        QtCore.QMetaObject.connectSlotsByName(FormAddCurator)

    def retranslateUi(self, FormAddCurator):
        _translate = QtCore.QCoreApplication.translate
        FormAddCurator.setWindowTitle(_translate("FormAddCurator", "Форма добавления куратора"))
        self.edit_name_curator.setPlaceholderText(_translate("FormAddCurator", "ФИО куратора"))
        self.label.setText(_translate("FormAddCurator", "Введите ФИО куратора"))
        self.btn_add_curator.setText(_translate("FormAddCurator", "Добавить куратора"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormAddCurator = QtWidgets.QMainWindow()
    ui = Ui_FormAddCurator()
    ui.setupUi(FormAddCurator)
    FormAddCurator.show()
    sys.exit(app.exec_())
