# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_group_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_group_window(object):
    def setupUi(self, main_group_window):
        main_group_window.setObjectName("main_group_window")
        main_group_window.resize(786, 424)
        main_group_window.setStyleSheet("background-color: rgb(198, 198, 198);")
        self.centralwidget = QtWidgets.QWidget(main_group_window)
        self.centralwidget.setObjectName("centralwidget")
        self.table_all_groups = QtWidgets.QTableWidget(self.centralwidget)
        self.table_all_groups.setGeometry(QtCore.QRect(10, 10, 531, 341))
        self.table_all_groups.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_all_groups.setObjectName("table_all_groups")
        self.table_all_groups.setColumnCount(4)
        self.table_all_groups.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_all_groups.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_all_groups.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_all_groups.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.table_all_groups.setHorizontalHeaderItem(3, item)
        self.btn_save_change = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_change.setGeometry(QtCore.QRect(550, 280, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save_change.setFont(font)
        self.btn_save_change.setStyleSheet("QPushButton {background-color: rgb(133, 125, 86); \n"
"color: White; border-radius: 10px;}\n"
"QPushButton:pressed {background-color:rgb(43, 252, 50) ; }")
        self.btn_save_change.setAutoDefault(False)
        self.btn_save_change.setDefault(False)
        self.btn_save_change.setFlat(False)
        self.btn_save_change.setObjectName("btn_save_change")
        self.btn_delete_group = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete_group.setGeometry(QtCore.QRect(550, 210, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delete_group.setFont(font)
        self.btn_delete_group.setStyleSheet("QPushButton {background-color: rgb(133, 125, 86); \n"
"color: White; border-radius: 10px;}\n"
"QPushButton:pressed {background-color:rgb(43, 252, 50) ; }")
        self.btn_delete_group.setAutoDefault(False)
        self.btn_delete_group.setDefault(False)
        self.btn_delete_group.setFlat(False)
        self.btn_delete_group.setObjectName("btn_delete_group")
        self.btn_out_all_groups = QtWidgets.QPushButton(self.centralwidget)
        self.btn_out_all_groups.setGeometry(QtCore.QRect(550, 10, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_out_all_groups.setFont(font)
        self.btn_out_all_groups.setStyleSheet("QPushButton {background-color: rgb(133, 125, 86); \n"
"color: White; border-radius: 10px;}\n"
"QPushButton:pressed {background-color:rgb(43, 252, 50) ; }")
        self.btn_out_all_groups.setAutoDefault(False)
        self.btn_out_all_groups.setDefault(False)
        self.btn_out_all_groups.setFlat(False)
        self.btn_out_all_groups.setObjectName("btn_out_all_groups")
        self.btn_open_add_group_form = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_add_group_form.setGeometry(QtCore.QRect(550, 90, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_add_group_form.setFont(font)
        self.btn_open_add_group_form.setStyleSheet("QPushButton {background-color: rgb(133, 125, 86); \n"
"color: White; border-radius: 10px;}\n"
"QPushButton:pressed {background-color:rgb(43, 252, 50) ; }")
        self.btn_open_add_group_form.setAutoDefault(False)
        self.btn_open_add_group_form.setDefault(False)
        self.btn_open_add_group_form.setFlat(False)
        self.btn_open_add_group_form.setObjectName("btn_open_add_group_form")
        self.cb_choice_filter = QtWidgets.QComboBox(self.centralwidget)
        self.cb_choice_filter.setGeometry(QtCore.QRect(10, 380, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_choice_filter.setFont(font)
        self.cb_choice_filter.setCurrentText("")
        self.cb_choice_filter.setObjectName("cb_choice_filter")
        self.cb_choice_filter.addItem("")
        self.cb_choice_filter.setItemText(0, "")
        self.cb_choice_filter.addItem("")
        self.cb_choice_filter.addItem("")
        self.cb_choice_filter.addItem("")
        self.edit_filter = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_filter.setEnabled(False)
        self.edit_filter.setGeometry(QtCore.QRect(220, 380, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.edit_filter.setFont(font)
        self.edit_filter.setObjectName("edit_filter")
        self.btn_out_criteria_group = QtWidgets.QPushButton(self.centralwidget)
        self.btn_out_criteria_group.setGeometry(QtCore.QRect(610, 370, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_out_criteria_group.setFont(font)
        self.btn_out_criteria_group.setStyleSheet("QPushButton {background-color: rgb(133, 125, 86); \n"
"color: White; border-radius: 10px;}\n"
"QPushButton:pressed {background-color:rgb(43, 252, 50) ; }")
        self.btn_out_criteria_group.setAutoDefault(False)
        self.btn_out_criteria_group.setDefault(False)
        self.btn_out_criteria_group.setFlat(False)
        self.btn_out_criteria_group.setObjectName("btn_out_criteria_group")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 355, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_change_curator = QtWidgets.QPushButton(self.centralwidget)
        self.btn_change_curator.setGeometry(QtCore.QRect(550, 140, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_change_curator.setFont(font)
        self.btn_change_curator.setStyleSheet("QPushButton {background-color: rgb(133, 125, 86); \n"
"color: White; border-radius: 10px;}\n"
"QPushButton:pressed {background-color:rgb(43, 252, 50) ; }")
        self.btn_change_curator.setAutoDefault(False)
        self.btn_change_curator.setDefault(False)
        self.btn_change_curator.setFlat(False)
        self.btn_change_curator.setObjectName("btn_change_curator")
        main_group_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_group_window)
        QtCore.QMetaObject.connectSlotsByName(main_group_window)

    def retranslateUi(self, main_group_window):
        _translate = QtCore.QCoreApplication.translate
        main_group_window.setWindowTitle(_translate("main_group_window", "Группы"))
        item = self.table_all_groups.horizontalHeaderItem(0)
        item.setText(_translate("main_group_window", "id"))
        item = self.table_all_groups.horizontalHeaderItem(1)
        item.setText(_translate("main_group_window", "Название группы"))
        item = self.table_all_groups.horizontalHeaderItem(2)
        item.setText(_translate("main_group_window", "Куратор группы"))
        item = self.table_all_groups.horizontalHeaderItem(3)
        item.setText(_translate("main_group_window", "Количество человек"))
        self.btn_save_change.setText(_translate("main_group_window", "Сохранить изменения\n"
"в таблице"))
        self.btn_delete_group.setText(_translate("main_group_window", "Удалить группу"))
        self.btn_out_all_groups.setText(_translate("main_group_window", "Вывести всю информацию\n"
"в таблицу"))
        self.btn_open_add_group_form.setText(_translate("main_group_window", "Добавить новую группу"))
        self.cb_choice_filter.setItemText(1, _translate("main_group_window", "id"))
        self.cb_choice_filter.setItemText(2, _translate("main_group_window", "Название группы"))
        self.cb_choice_filter.setItemText(3, _translate("main_group_window", "Куратор"))
        self.edit_filter.setPlaceholderText(_translate("main_group_window", "Выберите критерий в выпадающем списке"))
        self.btn_out_criteria_group.setText(_translate("main_group_window", "Вывести \n"
"по критерию"))
        self.label.setText(_translate("main_group_window", "Критерий выбора"))
        self.btn_change_curator.setText(_translate("main_group_window", "Изменить куратора\n"
"у группы"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_group_window = QtWidgets.QMainWindow()
    ui = Ui_main_group_window()
    ui.setupUi(main_group_window)
    main_group_window.show()
    sys.exit(app.exec_())
