# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_curator_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_curators_window(object):
    def setupUi(self, main_curators_window):
        main_curators_window.setObjectName("main_curators_window")
        main_curators_window.setEnabled(True)
        main_curators_window.resize(666, 465)
        main_curators_window.setStyleSheet("background-color: rgb(198, 198, 198);")
        self.centralwidget = QtWidgets.QWidget(main_curators_window)
        self.centralwidget.setObjectName("centralwidget")
        self.table_all_curators = QtWidgets.QTableWidget(self.centralwidget)
        self.table_all_curators.setGeometry(QtCore.QRect(10, 10, 411, 361))
        self.table_all_curators.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_all_curators.setObjectName("table_all_curators")
        self.table_all_curators.setColumnCount(3)
        self.table_all_curators.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_all_curators.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_all_curators.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_all_curators.setHorizontalHeaderItem(2, item)
        self.btn_save_change = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_change.setGeometry(QtCore.QRect(440, 290, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save_change.setFont(font)
        self.btn_save_change.setStyleSheet("QPushButton {background-color: rgb(133, 125, 86); \n"
"color: White; border-radius: 10px;}\n"
"QPushButton:pressed {background-color:rgb(43, 252, 50) ; }")
        self.btn_save_change.setAutoDefault(False)
        self.btn_save_change.setDefault(False)
        self.btn_save_change.setFlat(False)
        self.btn_save_change.setObjectName("btn_save_change")
        self.btn_open_add_curator_form = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_add_curator_form.setGeometry(QtCore.QRect(440, 90, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_add_curator_form.setFont(font)
        self.btn_open_add_curator_form.setStyleSheet("QPushButton {background-color: rgb(133, 125, 86); \n"
"color: White; border-radius: 10px;}\n"
"QPushButton:pressed {background-color:rgb(43, 252, 50) ; }")
        self.btn_open_add_curator_form.setAutoDefault(False)
        self.btn_open_add_curator_form.setDefault(False)
        self.btn_open_add_curator_form.setFlat(False)
        self.btn_open_add_curator_form.setObjectName("btn_open_add_curator_form")
        self.btn_delete_curator = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete_curator.setGeometry(QtCore.QRect(440, 240, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delete_curator.setFont(font)
        self.btn_delete_curator.setStyleSheet("QPushButton {background-color: rgb(133, 125, 86); \n"
"color: White; border-radius: 10px;}\n"
"QPushButton:pressed {background-color:rgb(43, 252, 50) ; }")
        self.btn_delete_curator.setAutoDefault(False)
        self.btn_delete_curator.setDefault(False)
        self.btn_delete_curator.setFlat(False)
        self.btn_delete_curator.setObjectName("btn_delete_curator")
        self.btn_out_all_curators = QtWidgets.QPushButton(self.centralwidget)
        self.btn_out_all_curators.setGeometry(QtCore.QRect(440, 10, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_out_all_curators.setFont(font)
        self.btn_out_all_curators.setStyleSheet("QPushButton {background-color: rgb(133, 125, 86); \n"
"color: White; border-radius: 10px;}\n"
"QPushButton:pressed {background-color:rgb(43, 252, 50) ; }")
        self.btn_out_all_curators.setAutoDefault(False)
        self.btn_out_all_curators.setDefault(False)
        self.btn_out_all_curators.setFlat(False)
        self.btn_out_all_curators.setObjectName("btn_out_all_curators")
        self.btn_out_flter_data = QtWidgets.QPushButton(self.centralwidget)
        self.btn_out_flter_data.setGeometry(QtCore.QRect(440, 410, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_out_flter_data.setFont(font)
        self.btn_out_flter_data.setStyleSheet("QPushButton {background-color: rgb(133, 125, 86); \n"
"color: White; border-radius: 10px;}\n"
"QPushButton:pressed {background-color:rgb(43, 252, 50) ; }")
        self.btn_out_flter_data.setAutoDefault(False)
        self.btn_out_flter_data.setDefault(False)
        self.btn_out_flter_data.setFlat(False)
        self.btn_out_flter_data.setObjectName("btn_out_flter_data")
        self.edit_filter = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_filter.setEnabled(False)
        self.edit_filter.setGeometry(QtCore.QRect(200, 410, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.edit_filter.setFont(font)
        self.edit_filter.setObjectName("edit_filter")
        self.cb_choice_filter = QtWidgets.QComboBox(self.centralwidget)
        self.cb_choice_filter.setGeometry(QtCore.QRect(10, 410, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_choice_filter.setFont(font)
        self.cb_choice_filter.setCurrentText("")
        self.cb_choice_filter.setObjectName("cb_choice_filter")
        self.cb_choice_filter.addItem("")
        self.cb_choice_filter.setItemText(0, "")
        self.cb_choice_filter.addItem("")
        self.cb_choice_filter.addItem("")
        self.cb_choice_filter.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 390, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_open_change_group = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_change_group.setGeometry(QtCore.QRect(440, 150, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_change_group.setFont(font)
        self.btn_open_change_group.setStyleSheet("QPushButton {background-color: rgb(133, 125, 86); \n"
"color: White; border-radius: 10px;}\n"
"QPushButton:pressed {background-color:rgb(43, 252, 50) ; }")
        self.btn_open_change_group.setAutoDefault(False)
        self.btn_open_change_group.setDefault(False)
        self.btn_open_change_group.setFlat(False)
        self.btn_open_change_group.setObjectName("btn_open_change_group")
        main_curators_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_curators_window)
        QtCore.QMetaObject.connectSlotsByName(main_curators_window)

    def retranslateUi(self, main_curators_window):
        _translate = QtCore.QCoreApplication.translate
        main_curators_window.setWindowTitle(_translate("main_curators_window", "Главная форма кураторов"))
        item = self.table_all_curators.horizontalHeaderItem(0)
        item.setText(_translate("main_curators_window", "id"))
        item = self.table_all_curators.horizontalHeaderItem(1)
        item.setText(_translate("main_curators_window", "ФИО куратора"))
        item = self.table_all_curators.horizontalHeaderItem(2)
        item.setText(_translate("main_curators_window", "Группа куратора"))
        self.btn_save_change.setText(_translate("main_curators_window", "Сохранить изменения\n"
"в таблице"))
        self.btn_open_add_curator_form.setText(_translate("main_curators_window", "Добавить нового\n"
"куратора"))
        self.btn_delete_curator.setText(_translate("main_curators_window", "Удалить куратора"))
        self.btn_out_all_curators.setText(_translate("main_curators_window", "Вывести всех кураторов \n"
"в таблицу"))
        self.btn_out_flter_data.setText(_translate("main_curators_window", "Вывести по критерию"))
        self.edit_filter.setPlaceholderText(_translate("main_curators_window", "Выберите критерий в выпадающем списке"))
        self.cb_choice_filter.setItemText(1, _translate("main_curators_window", "id"))
        self.cb_choice_filter.setItemText(2, _translate("main_curators_window", "ФИО"))
        self.cb_choice_filter.setItemText(3, _translate("main_curators_window", "Группа"))
        self.label.setText(_translate("main_curators_window", "Критерий выбора"))
        self.btn_open_change_group.setText(_translate("main_curators_window", "Изменить группу\n"
"у куратора"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_curators_window = QtWidgets.QMainWindow()
    ui = Ui_main_curators_window()
    ui.setupUi(main_curators_window)
    main_curators_window.show()
    sys.exit(app.exec_())
