# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(640, 255)
        MainWindow.setStyleSheet("background-color: rgb(198, 198, 198);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_open_window_student = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_window_student.setGeometry(QtCore.QRect(140, 160, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_window_student.setFont(font)
        self.btn_open_window_student.setStyleSheet("QPushButton {background-color: rgb(51,122,183); color: White; border-radius: 4px;}\n"
"QPushButton:pressed {background-color:rgb(31,101,163) ; }")
        self.btn_open_window_student.setCheckable(False)
        self.btn_open_window_student.setAutoDefault(False)
        self.btn_open_window_student.setDefault(False)
        self.btn_open_window_student.setFlat(False)
        self.btn_open_window_student.setObjectName("btn_open_window_student")
        self.btn_open_window_group = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_window_group.setGeometry(QtCore.QRect(140, 110, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_window_group.setFont(font)
        self.btn_open_window_group.setStyleSheet("QPushButton {background-color: rgb(51,122,183); color: White; border-radius: 4px;}\n"
"QPushButton:pressed {background-color:rgb(31,101,163) ; }")
        self.btn_open_window_group.setAutoDefault(False)
        self.btn_open_window_group.setDefault(False)
        self.btn_open_window_group.setFlat(False)
        self.btn_open_window_group.setObjectName("btn_open_window_group")
        self.btn_open_window_curator = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_window_curator.setGeometry(QtCore.QRect(140, 60, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_window_curator.setFont(font)
        self.btn_open_window_curator.setStyleSheet("QPushButton {background-color: rgb(51,122,183); color: White; border-radius: 4px;}\n"
"QPushButton:pressed {background-color:rgb(31,101,163) ; }")
        self.btn_open_window_curator.setAutoDefault(False)
        self.btn_open_window_curator.setDefault(False)
        self.btn_open_window_curator.setFlat(False)
        self.btn_open_window_curator.setObjectName("btn_open_window_curator")
        self.btn_create_db = QtWidgets.QPushButton(self.centralwidget)
        self.btn_create_db.setGeometry(QtCore.QRect(140, 210, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_create_db.setFont(font)
        self.btn_create_db.setStyleSheet("QPushButton {background-color: rgb(51,122,183); color: White; border-radius: 4px;}\n"
"QPushButton:pressed {background-color:rgb(31,101,163) ; }")
        self.btn_create_db.setCheckable(False)
        self.btn_create_db.setAutoDefault(False)
        self.btn_create_db.setDefault(False)
        self.btn_create_db.setFlat(False)
        self.btn_create_db.setObjectName("btn_create_db")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главное меню"))
        self.label.setText(_translate("MainWindow", "Информационная система заведующего отделением"))
        self.btn_open_window_student.setText(_translate("MainWindow", "Таблица Студентов"))
        self.btn_open_window_group.setText(_translate("MainWindow", "Таблица Группы"))
        self.btn_open_window_curator.setText(_translate("MainWindow", "Таблица Кураторов"))
        self.btn_create_db.setText(_translate("MainWindow", "Создать базу данных"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
